---
- name: Install prerequisites for Google Cloud SDK
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - gnupg
    state: present
    update_cache: true

- name: Add Google Cloud SDK apt repository key
  ansible.builtin.apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: Add Google Cloud SDK apt repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main"
    state: present
    filename: google-cloud-sdk

- name: Download Google Cloud SDK GPG key
  ansible.builtin.get_url:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    dest: /usr/share/keyrings/cloud.google.gpg
    mode: "0644"

- name: Install Google Cloud SDK
  ansible.builtin.apt:
    name: google-cloud-cli
    state: present
    update_cache: true
